server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&allowPublicKeyRetrieval=true
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5 #最小空闲链接
      idle-timeout: 1800000 #空闲连接存活时间，默认10minutes
      maximum-pool-size: 10
      auto-commit: true #从连接池返回的连接自动提交
      max-lifetime: 1800000 #连接最大存活时间
      connection-timeout: 3000 #连接超时时间，默认10minutes
      connection-test-query: select 1 #测试连接是否可用的查询语句

#  thymeleaf:
##    prefix: classpath:/templates
#    suffix: .html
#    servlet:
#      content-type: text/html
#    encoding: UTF-8
#    mode: HTML5
#    cache: false
#    check-template: true
#    check-template-location: true
#    enabled: true

  mybatis-plus:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.mybatis.boot.model
    configuration:
      cache-enabled: true
      map-underscore-to-camel-case: true

  rabbitmq:
    host: localhost # rabbitMQ的ip地址
    port: 5672 # 端口
    username: admin
    password: admin
    virtual-host: /

  redis:
    port: 6379
    host: localhost
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-idle: 200
        min-idle: 5
        max-wait: 10000ms
        max-active: 8
logging:
  level:
    com.example: debug
  pattern:
    dateformat: mm:ss.SSS

